### PR TITLE
[FIX] Mermaid

### LINKED ISSUE #3: [BUG] The mermaid graph has rendering error
https://hugodoit.pages.dev/theme-documentation-extended-shortcodes/#5-mermaid

Cannot display correctly.

The issue happens to classDiagram and gitGraph.

### PR DESCRIPTION
**Pull request by HEIGE-PCloud**
- Update mermaidjs to 8.9.3
- Update CDN
- Fix themeVariable
- Fix BlackMode CSS
- Fix tests and documentation

### CODE REVIEW

File: src/js/theme.js [hunk 1]
```diff
@@ -516,10 +516,11 @@ class Theme {
     initMermaid() {
         const $mermaidElements = document.getElementsByClassName('mermaid');
         if ($mermaidElements.length) {
-            mermaid.initialize({startOnLoad: false, theme: 'null'});
+            mermaid.initialize({startOnLoad: false, theme: 'default'});
```
Comment (HEIGE-PCloud) [inline src/js/theme.js:519]: `theme: null` does work in older version of mermaid but does not work in `^8.9.*` and set theme to `null` or `"null"` will cause different problems. This might be the issue with mermaid itself.

According to the docs, `null` should be a valid option: https://mermaid-js.github.io/mermaid/#/Setup?id=theme

Change theme to `default` or anything other than `null` will add inline `<style>` to the diagrams and overwrite the custom CSS, which result in a bad experience in dark mode.

File: src/js/theme.js [hunk 2]
```diff
@@ -516,10 +516,11 @@ class Theme {
...
             this.util.forEach($mermaidElements, $mermaid => {
                 mermaid.mermaidAPI.render('svg-' + $mermaid.id, this.data[$mermaid.id], svgCode => {
                     $mermaid.insertAdjacentHTML('afterbegin', svgCode);
+                document.getElementById('svg-' + $mermaid.id).children[0].remove();
```
Comment (HEIGE-PCloud) [inline src/js/theme.js:523]: To remove these default styles, a dirty work is done to remove them from the DOM. I am not quite happy with this implementation, but this is the only solution for the latest mermaid (other than adding thousands of `!important`). Hopefully they can fix their bugs very soon.

File: exampleSite/content/posts/tests/mermaid-tests/index.en.md [hunk 3]
```diff
@@ -44,8 +41,7 @@ Future task               :         des3, after des2, 5d
 Future task2               :         des4, after des3, 5d
 {{< /mermaid >}}
 
-{{< mermaid >}}
-classDiagram
+{{< mermaid >}}classDiagram
```
Comment (HEIGE-PCloud) [inline exampleSite/content/posts/tests/mermaid-tests/index.en.md:44]: This issue is only related to `classDiagram`. Adding `\r\n` before classDiagram will cause rendering issue. So for consistency, all `\r\n` are removed in markdown.

Again, I think this is a bug related to mermaid itself. But anyway.
